### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NightKoneko**
Made it better. You're welcome.

### CODE REVIEW

**Comment by Realswitzer** [comment]
no.

**Comment by Realswitzer** [comment]
literally 1984

**Comment by Realswitzer** [comment]
committing 1984 was a bit too harsh

**Comment by NightKoneko** [comment]
fixed i
0 (Small)
t

**Review by Realswitzer — APPROVED** [review]
fine

**Comment by NightKoneko** [comment]
lets gooooooo

**Pull request merged**
